### ISSUE TITLE
License of the project?

### ISSUE THREAD

**Issue by ad-si** [dkarter/fretmaster-elm#55]
Awesome project! I would like to use it as the basis for an explorer app for another instrument. Can you maybe add a license to the project, so that I know what I can and can't do? 😉
Thanks!

**Comment by dkarter** [comment]
Thank you for expressing interest in Fretmaster and for the kind words! I've added a license file for the project as GNU General Public License v3.0 hope that works out well for you and curious to see what you come up with.

I've been wanting to refactor this code for awhile now and make the fretboard component more.. functional! But it always turns into this really big project and I never get around to finishing it. There's a branch on this repo called "total-refactor" to give an idea of the direction I wanted to take this. Good luck and please if you don't mind post what you came up with :)

**Comment by ad-si** [comment]
Thanks, sure works for me. I also use some form of GPL most of the times 😊.

I'm still contemplating whether I should write it in Elm or PureScript (and whether I even have the time for another side project 😂), but I will let you know if I can get something built. 😛

**Comment by ad-si** [comment]
Oh btw: You might enjoy this blog post by me: https://adriansieber.com/ukulele-fingering-chart-cli-tool-in-haskell/ 😉
